"""[add] weight to sightings if karp or rat

Revision ID: 22f5f99efe66
Revises: 81affd3c80b4
Create Date: 2018-01-10 15:10:10.760334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22f5f99efe66'
down_revision = '81affd3c80b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.add_column('sightings', sa.Column('weight', mysql.DOUBLE(precision=18, scale=14), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_column('sightings', 'weight')   
    # ### end Alembic commands ###
