"""add sponsor

Revision ID: 5c44526548c3
Revises: 3af369660743
Create Date: 2017-11-09 12:29:58.283797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c44526548c3'
down_revision = '3af369660743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forts', sa.Column('sponsor', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forts', 'sponsor')
    # ### end Alembic commands ###
