"""create_weather

Revision ID: 905cf0f89f5c
Revises: 5c44526548c3
Create Date: 2017-12-19 06:57:19.061877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '905cf0f89f5c'
down_revision = '5c44526548c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s2_cell_id', sa.BigInteger(), nullable=True),
    sa.Column('condition', sa.SmallInteger(), nullable=True),
    sa.Column('alert_severity', sa.SmallInteger(), nullable=True),
    sa.Column('warn', sa.Boolean(), nullable=True),
    sa.Column('day', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    # ### end Alembic commands ###
