"""add weather to forts

Revision ID: 95ff6d6dd804
Revises: 6295b5d42e24
Create Date: 2018-01-02 16:40:23.237209

"""
from alembic import op
import sqlalchemy as sa
import sys
from pathlib import Path
monocle_dir = str(Path(__file__).resolve().parents[2])
if monocle_dir not in sys.path:
    sys.path.append(monocle_dir)
from monocle import db as db

# revision identifiers, used by Alembic.
revision = '95ff6d6dd804'
down_revision = '6295b5d42e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forts', sa.Column('weather_cell_id', db.UNSIGNED_HUGE_TYPE, nullable=True))
    op.create_index('ix_forts_weather_cell', 'forts', ['weather_cell_id'], unique=False)
    op.create_foreign_key('forts_fk_cellid', 'forts', 'weather', ['weather_cell_id'], ['s2_cell_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('forts_fk_cellid', 'forts', type_='foreignkey')
    op.drop_index('ix_forts_weather_cell', table_name='forts')
    op.drop_column('forts', 'weather_cell_id')
    # ### end Alembic commands ###
