"""add updated to weather

Revision ID: f13582bd37a0
Revises: c5e649196f94
Create Date: 2017-12-21 14:58:34.560435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f13582bd37a0'
down_revision = 'c5e649196f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('updated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather', 'updated')
    # ### end Alembic commands ###
